### CSV : sitemin.csv
    - 미니 버전 
        400*300

### load : 0  , load = 1 , caner = 2 , turn = 3
### home_ in : 4  , home_out : 5 , home point = 9
### M_in : 6  , M _out : 7
### check point1 = 8

In [1]:
import pandas as pd 
import numpy as np 

from pandas import DataFrame, Series

In [2]:
df = np.zeros(( 300, 400 ),int)
df, df.shape,df.dtype

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (300, 400), dtype('int32'))

In [3]:
df

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [4]:
# #  home1_in 그리기
# df[0:(0+30), 89-15:(89+15)] = 4
# df[0:(0+30),224-15:(224+15)] = 4
# #home2_out
# df[0:(0+30), 359-15:(359+15)] = 5
# df[0:(0+30), 494-15:(494+15)] = 5

In [5]:
#Load back side 
# 벽에서 로드 첫 좌표까지 
# 위
df[0:(0+15), :] = 1
#왼쪽 벽
df[15:(300-15), :15] = 1
# 오른쪽
df[15:300-15, 400-15:] = 1
# 아래
df[(300-15):, :] = 1

In [6]:
# 홈
df[0:(0+15), 89:(89+15)] = 4

In [7]:
df[0:(0+15),224+15:(224+15+15)] = 4

In [8]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/sitemin.csv", header = True, index = False )

In [9]:
data = pd.read_csv('./data/sitemin.csv')
# data

### 기계

In [10]:
# 기계 area1 
df[80:(80+60), 50:(50+50)] = 6
# 기계 area1-1   
df[80:(80+60), 125:(125+50)] = 6
df[80:(80+60), 200:(200+50)] = 6
df[80:(80+60), 275:(275+50)] = 6
# 기계 area 2-1
df[180:(180+60),50:(50+50)] = 5
df[180:(180+60),125:(125+50)] = 5
# 기계 area 2-4
df[180:(180+60),200:(200+50)] = 5
df[180:(180+60),275:(275+50)] = 5

In [11]:
a = df[:,:]
a,a.shape

(array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]]), (300, 400))

In [12]:
# 배열의 고유한 요소를 찾음 =>  각수자의 개수를 알려줌 
unique, counts = np.unique(a, return_counts= True)
dict(zip(unique, counts))

{0: 75900, 1: 19650, 4: 450, 5: 12000, 6: 12000}

In [13]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/sitemin.csv",header = True, index = False )

#  위치 설정 

 - home (in,out) : @2 
     - home1_in  : 
     - home2_out :
     
 - load
     - 직진 
     - 코너 
     - 회전 
     
 - Machine  
 >'ㄷ' 자로 만들어야해, 큰 사각형을 만들고 작은 사각형을 만들어야한다. 
     큰사각형 : 5
     작은 사각형은 : 6 
         - 정면 
         - 후면 
