### CSV : site3.csv

### load : 0  , load = 1 , caner = 2 , turn = 3
### home_ in : 4  , home_out : 5 , home point = 9
### M_in : 6  , M _out : 7
### check point1 = 8

In [1]:
import pandas as pd 
import numpy as np 

from pandas import DataFrame, Series

In [2]:
df = np.zeros(( 500, 600 ),int)
df, df.shape,df.dtype

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (500, 600), dtype('int32'))

In [3]:
df

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [2]:
# df[:,:] = 0
# df[:,:]

In [3]:
(-1+90),(89+15+120),(224+15+120),(359+15+120),(494+15+90)

(89, 224, 359, 494, 599)

#### home
 - home
 size = 15*\30
     - home1_in  : 4
     - home2_out : 5
     

In [4]:
#  home1_in 
df[0:(0+30), 89:(89+15)] = 4
df[0:(0+30),224:(224+15)] = 4
#home2_out
df[0:(0+30), 359:(359+15)] = 5
df[0:(0+30), 494:(494+15)] = 5

In [5]:
df[0:(0+30), 89:(89+15)],df[0:(0+30), 89:(89+15)].shape

(array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4

In [10]:
# 홈 포지션 간격
(-1+90),(89+15+120),(224+15+120),(359+15+120),(494+15+90)

(89, 224, 359, 494, 599)

In [11]:
390 -(120*3)-(15*2)

0

In [6]:
# home1_in 
df[0:(0+30),224:(224+15)],df[0:(0+30),224:(224+15)].shape

(array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4

In [13]:
#home2_out
df[0:(0+30), 359:(359+15)],df[0:(0+30), 359:(359+15)].shape

(array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5

In [7]:
#home2_out
df[0:(0+30), 494:(494+15)],df[0:(0+30), 494:(494+15)].shape

(array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
        [5

In [27]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/site3.csv", header = True, index = False )

In [28]:
data = pd.read_csv('./data/site3.csv')
data

0  1  2  3  4  5  6  7  8  9 ...   590  591  592  593  594  595  596  \
0    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
1    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
2    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
3    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
4    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
5    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
6    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
7    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
8    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
9    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
10   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
11   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
12   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
13   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
14   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
15   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
16   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
17   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
18   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
19   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
20   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
21   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
22   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
23   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
24   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
25   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
26   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
27   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
28   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
29   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
..  .. .. .. .. .. .. .. .. .. .. ...   ...  ...  ...  ...  ...  ...  ...   
470  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
471  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
472  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
473  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
474  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
475  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
476  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
477  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
478  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
479  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
480  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
481  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
482  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
483  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
484  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
485  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
486  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
487  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
488  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
489  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
4

In [17]:
# Home_pos = [[3 for i in range(15)] for j in range(30)]
# Home_pos

In [18]:
# Home = np.ones(( 15, 30 ),int)
# print(Home)
#  Home *= 2
# print(Home)
# print(type(df),type(Home)) 

In [19]:
# ch = df[0:15, :] 
# ch1 = df[79:109]
# ch,ch1,ch1.shape,ch.shape

In [11]:
data.iloc[2:, :].values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
df[0:(0+30), 79:(79+15)],df[0:(0+30), 79:(79+15)].shape

(array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4],
        [0

In [13]:
# doing
# slide_df_home =df[0:(0+30), 79:(79+15)] #15 * 30// 1부터 카운트 하는 이유는 컬럼때문에 
# slide_df_home, slide_df_home.shape,slide_df_home.dtype

In [14]:
# # slide_df_home[:,:] 
# slide_df_home[:,:] = 3
# df[78:119,1:17],df[78:119,1:17].shape

#### 길
 - load
 size = 
     - 직진 : 1
     - 코너 : 2
     - 회전 : 3
  - unload
      - 벽: 0

In [13]:
# 큰 사각형
df[60:(60+70), 100:(100+400)] = 1
#  작은 사각형 
df[60+20:(60+20+30), 100+20:(100+20+360)] = 0

In [14]:
# 큰 사각형
# df[60:(60+70), 100:(100+400)] = 1
df[60:(60+70), 100:(100+400)],df[60:(60+70), 100:(100+400)].shape

(array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]]), (70, 400))

In [15]:
#  작은 사각형 
# df[60+20:(60+20+30), 100+20:(100+20+360)] = 0
df[60+20:(60+20+30), 100+20:(100+20+360)],df[60+20:(60+20+30), 100+20:(100+20+360)].shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (30, 360))

In [25]:
500-50

450

In [16]:
#Load back side 
# 벽에서 로드 첫 좌표까지 
df[280:(280+10+30), 100:(100+400)] = 1
df[450:(450+10+30), 100:(100+400)] = 1

In [17]:
df[280:(280+10+30), 100:(100+400)],df[280:(280+10+30), 100:(100+400)].shape

(array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]]), (40, 400))

In [18]:
df[450:(450+10+30), 100:(100+400)],df[450:(450+10+30), 100:(100+400)].shape

(array([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        ...,
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1]]), (40, 400))

### 기계

In [19]:
# 기계 area1  # 30+36-16
df[160:(160+120), 55:(55+100)] = 6
# 기계 area1-1   
df[160:(160+120), 185:(185+100)] = 6


In [20]:
# 기계 area1  # 30+36-16
# df[160:(160+120), 55:(55+100)] = 6
df[160:(160+120), 55:(55+100)] ,df[160:(160+120), 55:(55+100)].shape

(array([[6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        ...,
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6]]), (120, 100))

In [21]:
# 기계 area1-1  
# df[160:(160+120), 185:(185+100)] = 6
df[160:(160+120), 185:(185+100)] ,df[160:(160+120), 55:(55+100)].shape

(array([[6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        ...,
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6]]), (120, 100))

In [25]:
160+120+30,55+100+30

(310, 185)

In [22]:
# 기계 area 2 # 30+36-16
df[310:(310+120), 185:(185+100)] = 6
df[310:(310+120), 185:(185+100)],df[310:(310+120), 185:(185+100)].shape

(array([[6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        ...,
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6],
        [6, 6, 6, ..., 6, 6, 6]]), (120, 100))

In [23]:
Area_1 = df[160:(160+120), 55:(55+100)] 
Area_2 = df[310:(310+120), 185:(185+100)]

In [24]:
Area_1.shape,Area_2.shape

((120, 100), (120, 100))

In [ ]:
# 반복문으로 짜보고싶은데 지금시간이 없으니까 노가다 ^^

In [25]:
a = df[:,:]
a,a.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (500, 600))

In [26]:
# 배열의 고유한 요소를 찾음 =>  각수자의 개수를 알려줌 
unique, counts = np.unique(a, return_counts= True)
dict(zip(unique, counts))

{0: 214000, 1: 48200, 4: 900, 5: 900, 6: 36000}

In [13]:
30*15,500*600, 300000-450 , 4*450

(450, 300000, 299550, 1800)

In [29]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/site3.csv",header = True, index = False )

In [31]:
type(df)

numpy.ndarray

#  위치 설정 

 - home (in,out) : @2 
     - home1_in  : 
     - home2_out :
     
 - load
     - 직진 
     - 코너 
     - 회전 
     
 - Machine  
 >'ㄷ' 자로 만들어야해, 큰 사각형을 만들고 작은 사각형을 만들어야한다. 
     큰사각형 : 5
     작은 사각형은 : 6 
         - 정면 
         - 후면 
