In [1]:
import pandas as pd 
import numpy as np 

from pandas import DataFrame, Series

In [17]:
df = np.zeros(( 501, 600 ),int)
df, df.shape,df.dtype

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (501, 600), dtype('int32'))

In [18]:
df[:,:] = 0

In [20]:
# home 1
df[0:(0+30), 79:(79+15)] = 3
df[0:(0+30), 79:(79+15)],df[0:(0+30), 79:(79+15)].shape

(array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3

In [5]:
(-1+80),(79+15+80),(174+15+140),(329+15+80),(424+15)

(79, 174, 329, 424, 439)

In [6]:
289+15

304

In [21]:
#home 2
df[0:(0+30),174:(174+15)] = 3
df[0:(0+30),174:(174+15)],df[0:(0+30),174:(174+15)].shape

(array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3

In [22]:
# home 3
df[0:(0+30), 329:(329+15)] = 4
df[0:(0+30), 329:(329+15)],df[0:(0+30), 329:(329+15)].shape

(array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4

In [23]:
# home 4
df[0:(0+30), 424:(424+15)] = 4
df[0:(0+30), 424:(424+15)],df[0:(0+30), 424:(424+15)].shape

(array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
        [4

In [24]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/site3.csv",header = False, index = False )

In [30]:
df = pd.read_csv('./data/site1.csv')
df

0  1  2  3  4  5  6  7  8  9 ...   590  591  592  593  594  595  596  \
0    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
1    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
2    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
3    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
4    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
5    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
6    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
7    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
8    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
9    0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
10   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
11   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
12   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
13   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
14   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
15   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
16   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
17   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
18   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
19   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
20   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
21   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
22   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
23   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
24   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
25   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
26   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
27   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
28   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
29   0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
..  .. .. .. .. .. .. .. .. .. .. ...   ...  ...  ...  ...  ...  ...  ...   
470  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
471  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
472  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
473  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
474  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
475  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
476  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
477  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
478  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
479  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
480  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
481  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
482  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
483  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
484  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
485  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
486  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
487  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
488  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
489  0  0  0  0  0  0  0  0  0  0 ...     0    0    0    0    0    0    0   
4

In [25]:
path = './data/'
Site = pd.read_csv( path + 'site3.csv' )
Site0	0.1	0.2	0.3	0.4	0.5	0.6	0.7	0.8	0.9	...	0.530	0.531	0.532	0.533	0.534	0.535	0.536	0.537	0.538	0.539

0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  ...    0.530  0.531  \
0    0    0    0    0    0    0    0    0    0    0  ...        0      0   
1    0    0    0    0    0    0    0    0    0    0  ...        0      0   
2    0    0    0    0    0    0    0    0    0    0  ...        0      0   
3    0    0    0    0    0    0    0    0    0    0  ...        0      0   
4    0    0    0    0    0    0    0    0    0    0  ...        0      0   
5    0    0    0    0    0    0    0    0    0    0  ...        0      0   
6    0    0    0    0    0    0    0    0    0    0  ...        0      0   
7    0    0    0    0    0    0    0    0    0    0  ...        0      0   
8    0    0    0    0    0    0    0    0    0    0  ...        0      0   
9    0    0    0    0    0    0    0    0    0    0  ...        0      0   
10   0    0    0    0    0    0    0    0    0    0  ...        0      0   
11   0    0    0    0    0    0    0    0    0    0  ...        0      0   
12   0    0    0    0    0    0    0    0    0    0  ...        0      0   
13   0    0    0    0    0    0    0    0    0    0  ...        0      0   
14   0    0    0    0    0    0    0    0    0    0  ...        0      0   
15   0    0    0    0    0    0    0    0    0    0  ...        0      0   
16   0    0    0    0    0    0    0    0    0    0  ...        0      0   
17   0    0    0    0    0    0    0    0    0    0  ...        0      0   
18   0    0    0    0    0    0    0    0    0    0  ...        0      0   
19   0    0    0    0    0    0    0    0    0    0  ...        0      0   
20   0    0    0    0    0    0    0    0    0    0  ...        0      0   
21   0    0    0    0    0    0    0    0    0    0  ...        0      0   
22   0    0    0    0    0    0    0    0    0    0  ...        0      0   
23   0    0    0    0    0    0    0    0    0    0  ...        0      0   
24   0    0    0    0    0    0    0    0    0    0  ...        0      0   
25   0    0    0    0    0    0    0    0    0    0  ...        0      0   
26   0    0    0    0    0    0    0    0    0    0  ...        0      0   
27   0    0    0    0    0    0    0    0    0    0  ...        0      0   
28   0    0    0    0    0    0    0    0    0    0  ...        0      0   
29   0    0    0    0    0    0    0    0    0    0  ...        0      0   
..  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...      ...    ...   
470  0    0    0    0    0    0    0    0    0    0  ...        0      0   
471  0    0    0    0    0    0    0    0    0    0  ...        0      0   
472  0    0    0    0    0    0    0    0    0    0  ...        0      0   
473  0    0    0    0    0    0    0    0    0    0  ...        0      0   
474  0    0    0    0    0    0    0    0    0    0  ...        0      0   
475  0    0    0    0    0    0    0    0    0    0  ...        0      0   
476  0    0    0    0    0    0    0    0    0    0  ...        0      0   
477  0    0    0    0    0    0    0    0    0    0  ...        0      0   
478  0    0    0    0    0    0    0    0    0    0  ...        0      0   
479  0    0    0    0    0    0    0    0    0    0  ...        0      0   
480  0    0    0    0    0    0    0    0    0    0  ...        0      0   
481  0    0    0    0    0    0    0    0    0    0  ...        0      0   
482  0    0    0    0    0    0    0    0    0    0  ...        0      0   
483  0    0    0    0    0    0    0    0    0    0  ...        0      0   
484  0    0    0    0    0    0    0    0    0    0  ...        0      0   
485  0    0    0    0    0    0    0    0    0    0  ...        0      0   
486  0    0    0    0    0    0    0    0    0    0  ...        0      0   
487  0    0    0    0    0    0    0    0    0    0  ...        0      0   
488  0    0    0    0    0    0    0    0    0    0  ...        0      0   
489  0    0    0    0    0    0    0    0    0    0  ...        0      0   
490  0    0    0    0    0    0    0    0    0    0  

In [7]:
# Home_pos = [[3 for i in range(15)] for j in range(30)]
# Home_pos

In [51]:
pygame.event.get()

NameError: name 'pygame' is not defined

In [8]:
# Home = np.ones(( 15, 30 ),int)
# print(Home)
#  Home *= 2
# print(Home)
# print(type(df),type(Home)) 

In [9]:
# ch = df[0:15, :] 
# ch1 = df[79:109]
# ch,ch1,ch1.shape,ch.shape

In [10]:
Site.iloc[2:, :].values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [26]:
# df[79:109,0:15] = 3
# df[79:109,0:15].shape
df[0:(0+30), 79:(79+15)],df[0:(0+30), 79:(79+15)].shape

(array([[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
        [3

In [12]:
df[78:89,0:16].shape

(11, 16)

In [13]:
# doing
# slide_df_home =df[0:(0+30), 79:(79+15)] #15 * 30// 1부터 카운트 하는 이유는 컬럼때문에 
# slide_df_home, slide_df_home.shape,slide_df_home.dtype

In [14]:
# # slide_df_home[:,:] 
# slide_df_home[:,:] = 3
# df[78:119,1:17],df[78:119,1:17].shape

In [13]:
30*15,500*600, 300000-450 , 4*450

(450, 300000, 299550, 1800)

In [27]:
a = df[:,:]
a,a.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (501, 600))

In [28]:
# 배열의 고유한 요소를 찾음 =>  각수자의 개수를 알려줌 
unique, counts = np.unique(a, return_counts= True)
dict(zip(unique, counts))

{0: 298800, 3: 900, 4: 900}

In [29]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/site3.csv",header = False, index = False )

In [19]:
# np.savetxt("./data/site2.csv", df, delimiter=",")

In [21]:
type(Site)

pandas.core.frame.DataFrame

In [21]:
type(Site)

pandas.core.frame.DataFrame

#  위치 설정 
 - home (in,out) : @2 
     - in  : 앞에서 부터 
     - out :


In [22]:
# for i in range(15):
#     for j in range(30):
#         print( '2', j, sep='',end='')
#     print('i',2,sep ='',end='')