In [1]:
import pandas as pd
import numpy as np

In [2]:
grid = [[0 for x in range(60)] for y in range(50)]

In [7]:
# 배열에서 좌표값을 찾는법 

In [25]:
type(grid)

list

In [4]:
dataframe = pd.DataFrame( grid )
dataframe.to_csv( "./data/MinSite.csv", header = True, index = False )

In [5]:
data = pd.read_csv('./data/MinSite.csv')
# data

In [19]:
data

0  1  2  3  4  5  6  7  8  9 ...  50  51  52  53  54  55  56  57  58  59
0   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
1   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
2   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
3   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
4   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
5   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
6   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
7   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
8   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
9   0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
10  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
11  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
12  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
13  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
14  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
15  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
16  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
17  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
18  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
19  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
20  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
21  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
22  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
23  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
24  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
25  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
26  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
27  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
28  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
29  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
30  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
31  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
32  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
33  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
34  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
35  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
36  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
37  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
38  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
39  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
40  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
41  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
42  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
43  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
44  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
45  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
46  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
47  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
48  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0
49  0  0  0  0  0  0  0  0  0  0 ...   0   0   0   0   0   0   0   0   0   0

[50 rows x 60 columns]

In [26]:
a = np.array(data)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
data.values

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [23]:
np.array(int(data.iloc[:][:])

SyntaxError: unexpected EOF while parsing (<ipython-input-23-2da47066433a>, line 1)

In [26]:
data.dtypes

0     int64
1     int64
2     int64
3     int64
4     int64
5     int64
6     int64
7     int64
8     int64
9     int64
10    int64
11    int64
12    int64
13    int64
14    int64
15    int64
16    int64
17    int64
18    int64
19    int64
20    int64
21    int64
22    int64
23    int64
24    int64
25    int64
26    int64
27    int64
28    int64
29    int64
30    int64
31    int64
32    int64
33    int64
34    int64
35    int64
36    int64
37    int64
38    int64
39    int64
40    int64
41    int64
42    int64
43    int64
44    int64
45    int64
46    int64
47    int64
48    int64
49    int64
50    int64
51    int64
52    int64
53    int64
54    int64
55    int64
56    int64
57    int64
58    int64
59    int64
dtype: object

In [14]:
Series( data, index = 지정하고 싶은 index list )

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [5]:
data.index.values

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)