### CSV : site3.csv

### load : 0  , load = 1 , caner = 2 , turn = 3
### home_ in : 4  , home_out : 5 , home point = 9
### M_in : 6  , M _out : 7
### check point1 = 8

In [14]:
import pandas as pd 
import numpy as np 

from pandas import DataFrame, Series

In [15]:
df = np.zeros(( 300, 400 ),int)
df, df.shape,df.dtype

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (300, 400), dtype('int32'))

In [16]:
df

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [17]:
# #  home1_in 그리기
# df[0:(0+30), 89-15:(89+15)] = 4
# df[0:(0+30),224-15:(224+15)] = 4
# #home2_out
# df[0:(0+30), 359-15:(359+15)] = 5
# df[0:(0+30), 494-15:(494+15)] = 5

In [18]:
# 홈_ 벽
# df[:, :] = 0

In [19]:
# 홈_ 벽
df[30:370, 30:270] = 1

In [20]:
# 홈
df[0:(0+30), 89-15:(89+15)] = 4
df[0:(0+30),224-15:(224+15)] = 5

In [21]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/sitemin.csv", header = True, index = False )

In [22]:
data = pd.read_csv('./data/sitemin.csv')
# data

#### 길
 - load
 size = 
     - 직진 : 1
     - 코너 : 2
     - 회전 : 3
  - unload
      - 벽: 0

### 기계

In [23]:
# 기계 area1 
df[80:(80+60), 50:(50+50)] = 6
# 기계 area1-1   
df[80:(80+60), 125:(125+50)] = 6

# 기계 area 2-1
df[160:(160+60), 25:(25+50)] = 6

In [24]:
a = df[:,:]
a,a.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (300, 400))

In [25]:
# 배열의 고유한 요소를 찾음 =>  각수자의 개수를 알려줌 
unique, counts = np.unique(a, return_counts= True)
dict(zip(unique, counts))

{0: 36300, 1: 72900, 4: 900, 5: 900, 6: 9000}

In [26]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/sitemin.csv",header = True, index = False )

#  위치 설정 

 - home (in,out) : @2 
     - home1_in  : 
     - home2_out :
     
 - load
     - 직진 
     - 코너 
     - 회전 
     
 - Machine  
 >'ㄷ' 자로 만들어야해, 큰 사각형을 만들고 작은 사각형을 만들어야한다. 
     큰사각형 : 5
     작은 사각형은 : 6 
         - 정면 
         - 후면 
