### CSV : site3.csv

### load : 0  , load = 1 , caner = 2 , turn = 3
### home_ in : 4  , home_out : 5 , home point = 9
### M_in : 6  , M _out : 7
### check point1 = 8

In [4]:
import pandas as pd 
import numpy as np 

from pandas import DataFrame, Series

In [5]:
df = np.zeros(( 500, 600 ),int)
df, df.shape,df.dtype

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (500, 600), dtype('int32'))

In [145]:
df

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### home
 - home
 size = 15*\30
     - home1_in  : 4
     - home2_out : 5
     

In [146]:
#  home1_in 그리기
df[0:(0+30), 89-15:(89+15)] = 4
df[0:(0+30),224-15:(224+15)] = 4
#home2_out
df[0:(0+30), 359-15:(359+15)] = 5
df[0:(0+30), 494-15:(494+15)] = 5

In [147]:
#Load back side 
# 벽에서 로드 첫 좌표까지 
df[30:(30+30), 89-8:(89+8)] = 1
df[30:(30+30), 224-8:(224+8)] = 1
df[30:(30+30), 359-8:(359+8)] = 1
df[30:(30+30), 494-8:(494+8)] = 1

In [6]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/site1.csv", header = True, index = False )

In [7]:
data = pd.read_csv('./data/site1.csv')
# data

#### 길
 - load
 size = 
     - 직진 : 1
     - 코너 : 2
     - 회전 : 3
  - unload
      - 벽: 0

In [150]:
# 큰 사각형
df[50:(50+80), 10:590]= 1
#  작은 사각형 
df[70:(70+40), 20+10:(590-20)] = 0

In [151]:
#Load back side 
# 벽에서 로드 첫 좌표까지 
df[280+15:(295+20), 10:590] = 1
df[450+15:(465+20), 10:590] = 1

### 기계

In [152]:
#Load back side 
# 
df[160-30:(160), 55+42:(55+42+16)] = 1
df[160-30:(160), 185+42:(185+42+16)] = 1
df[160-30:(160), 315+42:(315+42+16)] = 1
df[160-30:(160), 445+42:(445+42+16)] = 1

In [153]:
#Load back side 
#  
df[330-60:(330), 55+42:(55+42+16)] = 1
df[330-60:(330), 185+42:(185+42+16)] = 1
df[330-60:(330), 315+42:(315+42+16)] = 1
df[330-60:(330), 445+42:(445+42+16)] = 1
# 
df[450:(450+45), 55+42:(55+42+16)] = 1
df[450:(450+45), 185+42:(185+42+16)] = 1
df[450:(450+45), 315+42:(315+42+16)] = 1
df[450:(450+45), 445+42:(445+42+16)] = 1


In [154]:
# 기계 area1 
df[160:(160+120), 55:(55+100)] = 6
# 기계 area1-1   
df[160:(160+120), 185:(185+100)] = 6
# 기계 area1 
df[160:(160+120), 315:(315+100)] = 6
# 기계 area1-1   
df[160:(160+120), 445:(445+100)] = 6

# 기계 area 2-1
df[330:(330+120), 55:(55+100)] = 6
# 기계 area 2-2
df[330:(330+120), 185:(185+100)] = 6
# 기계 area 2-3
df[330:(330+120), 315:(315+100)] = 6
# 기계 area 2-4
df[330:(330+120), 445:(445+100)] = 6

In [155]:
a = df[:,:]
a,a.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]), (500, 600))

In [8]:
# 배열의 고유한 요소를 찾음 =>  각수자의 개수를 알려줌 
unique, counts = np.unique(data, return_counts= True)
dict(zip(unique, counts))

{0: 300000}

In [157]:
dataframe = pd.DataFrame( df )
dataframe.to_csv( "./data/site3.csv",header = True, index = False )

#  위치 설정 

 - home (in,out) : @2 
     - home1_in  : 
     - home2_out :
     
 - load
     - 직진 
     - 코너 
     - 회전 
     
 - Machine  
 >'ㄷ' 자로 만들어야해, 큰 사각형을 만들고 작은 사각형을 만들어야한다. 
     큰사각형 : 5
     작은 사각형은 : 6 
         - 정면 
         - 후면 
